### ISSUE TITLE
Increase Job storage Size

### ISSUE THREAD

**Issue by tomyitav** [TotallyGatsby/DroneYard#3]
Hi, thanks for putting up this great project!

When parsing a large capture, I encountered the following error:
Attempt to create new tiff file '/code/opensfm/undistorted/images/M102_DJI_0427.JPG.tif' failed: No space left on device

How should I configure the Job / Instance storage?

**Comment by TotallyGatsby** [comment]
I've been using instances with a large amount of instance storage. I use an r6gd.4xlarge instance for mine, as I'm usually processing about 15-20GB of input images when I run my tasks.

Hypothetically, it would be possible to spin up EBS and mount it to the instance, but I haven't invested in that effort yet.
