### ISSUE TITLE
DroneYardJobQueue execution fails with error "exec /entry.sh: exec format error"

### ISSUE THREAD

**Issue by vinayngithub** [TotallyGatsby/DroneYard#4]
Problem Statement

Where can i verify more logs to identify the exact problem. I also added the Platform type as LINUX.AMD64 for publishing the build. Still seeing this error
_exec /entry.sh: exec format error_

Does this look like a image issue?
![image](https://github.com/TotallyGatsby/DroneYard/assets/102508642/881efc36-4354-4439-953b-03d21d8718dd)

**Comment by vinayngithub** [comment]
@TotallyGatsby can you please comment? Please note that this is Windows machine from where i am deploying. My changes to the DroneYardStack.js include the following

 ```
import * as iam from 'aws-cdk-lib/aws-iam';
 import * as s3Deploy from 'aws-cdk-lib/aws-s3-deployment';
-import { DockerImageAsset } from 'aws-cdk-lib/aws-ecr-assets';
+import { DockerImageAsset, Platform } from 'aws-cdk-lib/aws-ecr-assets';
 import { Duration } from 'aws-cdk-lib';

@@ -85,6 +86,7 @@ export default function DroneYardStack({ app, stack }) {
   // Create our guest image (e.g. the docker image from the DockerFile)
   const dockerImage = new DockerImageAsset(stack, 'DroneYardDockerImage', {
     directory: path.join(__dirname, awsConfig.computeEnv.useGpu ? 'dockergpu' : 'docker'),
+    platform: Platform.LINUX_AMD64
   });
```

**Comment by TotallyGatsby** [comment]
I'm updating this project today, and I'll see if I encounter this. I just deployed a fresh stack from my machine with a fresh version of the repo, however I'm not on a Windows machine (I'm on a mac). I'll see if the new version can successfully launch a batch.

**Comment by TotallyGatsby** [comment]
Starting from a blank slate (git clone), I ran the instructions in the readme and it successfully deployed and is currently processing some data from my most recent drone flight. 

What instance type are you running on?

**Comment by dylanirion** [comment]
I would imagine you want Platform.LINUX_ARM64 rather than AMD64 if you are using any of the gravitron instances (R6g)

**Comment by vinayngithub** [comment]
It was the default instance type that was cauing the issue earlier, the platform i want to run is AMD64 .. after changing the instance type to the one that supports AMD64 it started working.
