### ISSUE TITLE
outdated cdk package using deprecated python3.7 runtime for lambda

### ISSUE THREAD

**Issue by dylanirion** [TotallyGatsby/DroneYard#5]
I was getting an error on initial deploy that a BucketNotification lambda was being created using the deprecated python3.7 runtime.
I suspect it's coming from the `aws-batch-alpha` package. I had to bump `sst` all the way to [2.0.1](https://docs.sst.dev/upgrade-guide#upgrade-to-v20) to get a cdk package with a supported python runtime.

Do you want a PR? The changes aren't too major

**Comment by TotallyGatsby** [comment]
Sure! I'd be happy to merge in a PR. I have a copy of this running and haven't had to deploy a new one in a while, but I know that the Python deprecation is going to be coming for me someday.
